name: CI/CD 3-Tier App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@52.91.3.193:/home/ubuntu/app

    - name: Deploy with Docker
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.91.3.193 << 'EOF'
        cd /home/ubuntu/app
        docker-compose down
        docker-compose up -d --build
        EOF
